### ISSUE TITLE
CapturePNG2 is Gone

### ISSUE THREAD

**Issue by tireyfi1** [sysconf16/sysconf16.github.io#2]
On the [OS Tools](https://sysconf16.github.io/software/desktop-tools-scripts/os-tools.html) page, the download link provided for [CapturePNG2](https://hwbotdownloads.s3.amazonaws.com/downloads/benchmarks/CapturePNG2.exe) redirects to an access denied page. Looking around there don't seem to be any other mirrors of the program hosted anywhere else online either. If you still have a copy of it would be great to reupload it so that it doesn't become lost media.

**Comment by sysconf16** [comment]
Apologies, I don't have any backups.
After doing some digging, it looks like the AWS used by HWBOT has been closed, so all of the files stored on there are no longer accessible.

I'll keep an eye out to see if I can find another copy online, otherwise, I'd suggest either keeping an eye out/asking here: https://community.hwbot.org/topic/233924-benchmark-tweak-software-2024/, or contacting Luumi or any of the other tuners in the scene at the moment.
