### ISSUE TITLE
Windows 11 IoT Enteprise LTSC 2024

### ISSUE THREAD

**Issue by gabriellyonnet** [sysconf16/sysconf16.github.io#3]
Hello,

In Information > Technology > Guides, tell about Windows 11 IoT Entreprise LTSC 2024, which rolled out on the 1st of October 2024 because you still only tell about Windows 10 IoT Entreprise LTSC 2021. Also, arrange things by products like "this is for Windows 10 IoT Entreprise LTSC 2021", "this is for Windows 11 IoT Entreprise LTSC 2024" etc. And verify other things like that if you find anything and update the site accordingly.

Thanks.

**Comment by sysconf16** [comment]
A guide for Windows 10 IoT Enterprise LTSC 2021 will likely not be available for a while.

Firstly, due to the time it takes to properly understand how to optimise the OS for daily use and then write a guide accordingly, but also because I've not needed to use it myself yet.

Windows 10 will remain a better foundation due to its versatility and more lightweight base.
There's no need to switch away unless you're using an AMD X3D based system, or Intel system with P/E-cores, which will require the Windows 11 scheduler for optimal performance.

Please keep an eye out for if this changes, but I don't anticipate this being the case until at least another year.
